data:extend({
  {
    type = "double-setting",
    name = "dieselTrains_diesel_fuel_mj",
    order = "BA0",
    setting_type = "startup",
    default_value = 1.4,
    minimum_value = 0,
  }, {
    type = "double-setting",
    name = "dieselTrains_diesel_accel_mult",
    order = "BA1",
    setting_type = "startup",
    default_value = 1.2,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "dieselTrains_diesel_topspeed_mult",
    order = "BA2",
    setting_type = "startup",
    default_value = 1.1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "dieselTrains_light_oil_fuel_mj",
    order = "BB0",
    setting_type = "startup",
    default_value = 1.35,
    minimum_value = 0,
  },
{
    type = "double-setting",
    name = "dieselTrains_light_oil_accel_mult",
    order = "BB1",
    setting_type = "startup",
    default_value = 1.2,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "dieselTrains_light_oil_topspeed_mult",
    order = "BB2",
    setting_type = "startup",
    default_value = 1.1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "dieselTrains_heavy_oil_fuel_mj",
    order = "BC0",
    setting_type = "startup",
    default_value = 0.65,
    minimum_value = 0,
  },
{
    type = "double-setting",
    name = "dieselTrains_heavy_oil_accel_mult",
    order = "BC1",
    setting_type = "startup",
    default_value = 1.1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    order = "BC2",
    name = "dieselTrains_heavy_oil_topspeed_mult",
    setting_type = "startup",
    default_value = 1.05,
    minimum_value = 0,
  },
})
